name: offline_sync_example
description: Example app demonstrating Offline Sync Pack
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  offline_sync_pack:
    path: ../../sdk_products/offline_sync_pack

dev_dependencies:
  flutter_test:
    sdk: flutter
